import Head from 'next/head';
import MainLayout from '../components/layout';

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>CSU - Computer Science</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='flex items-center justify-center'>
          <h1 className='text-red-500'>
            Welcome to CSU - Computer Science Department
          </h1>
        </div>
      </main>
    </MainLayout>
  );
}
