import Head from 'next/head';
import Landing from '../components/landing';

export default function Home() {
  return (
    <>
      <Head>
        <title>CSU - Computer Science</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Landing />
    </>
  );
}
